name: new_food_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  html: ^0.15.0
  web_scraper: ^0.1.4
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cousine
      fonts:
        - asset: assets/Cousine-Regular.ttf
    - family: LibreBaskerville
      fonts:
        - asset: assets/LibreBaskerville-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/NotoSans-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Thin.ttf
    - family: Bitter
      fonts:
        - asset: assets/Bitter-VariableFont_wght.ttf
  assets:
    - assets/photos/bg.jpg
    - assets/fourty-one-2-1200x600.jpg
    - assets/fourty-one-sq.jpg

